### ISSUE TITLE
Unable to get Points Value

### ISSUE THREAD

**Issue by jdkeller** [Mephiles/torntools_extension#708]
```
TypeError: Cannot read properties of undefined (reading 'points_averagecost')
TypeError: Cannot read properties of undefined (reading 'points_averagecost')
    at showValue (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/features/points-value/ttPointsValue.js:45:32)
    at async FeatureManager.executeFunction (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/global/featureManager.js:233:51)
    at async FeatureManager.startFeature (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/global/featureManager.js:142:6)
```

**Comment by DeKleineKobini** [comment]
Any other feature broken (like quick items)?

**Comment by jdkeller** [comment]
Not that I see.

**Comment by jdkeller** [comment]
Seems to be working now.

**Comment by DeKleineKobini** [comment]
I'll be closing it for now then.
