### ISSUE TITLE
torntools broken without hint of explanation

### ISSUE THREAD

**Issue by sykoe** [Mephiles/torntools_extension#746]
sadly I dont know what exactly triggers it, but these are the errors i get on the homepage of torn: 

`
TypeError: userdata.refills is undefined
applyStyle@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/features/highlight-energy-refill/ttHighlightEnergyRefill.entry.js:22:7
executeFunction@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:234:9
startFeature@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:162:15
TypeError: userdata.refills is undefined
applyStyle@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/features/highlight-energy-refill/ttHighlightEnergyRefill.entry.js:22:7
executeFunction@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:234:9
startFeature@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:142:17
TypeError: userdata.refills is undefined
applyStyle@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/features/highlight-nerve-refill/ttHighlightNerveRefill.entry.js:22:7
executeFunction@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:234:9
startFeature@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:162:15
TypeError: userdata.refills is undefined
applyStyle@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/features/highlight-nerve-refill/ttHighlightNerveRefill.entry.js:22:7
executeFunction@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:234:9
startFeature@moz-extension://23e98e82-5efa-4c07-a341-fe087aa6310d/scripts/global/featureManager.js:142:17
— sidebar —
Company Addiction Level
Highlight Energy Refill
Highlight Nerve Refill
`

The only thing that fixed it for me was, Addons -> TornTools (optional: -> mange -> options -> backup) -> remove addon -> reinstall addon (-> import settings) 

after I do that it works for a while until it breaks again. 

Somehow torntools break on my chrome too, but a different error 
`
TypeError: Cannot read properties of undefined (reading 'useractivity')
TypeError: Cannot read properties of undefined (reading 'useractivity')
    at Object.stats (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/features/achievements/achievements.js:26:50)
    at chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/features/achievements/ttAchievements.entry.js:76:39
    at Array.forEach (<anonymous>)
    at fillGoals (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/features/achievements/ttAchievements.entry.js:75:17)
    at showAchievements (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/features/achievements/ttAchievements.entry.js:61:3)
    at async FeatureManager.executeFunction (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/global/featureManager.js:233:51)
    at async FeatureManager.startFeature (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/global/featureManager.js:142:6)
TypeError: Cannot read properties of undefined (reading 'total')
TypeError: Cannot read properties of undefined (reading 'total')
    at showNetworth (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/features/live-networth/ttLiveNetworth.js:33:83)
    at async FeatureManager.executeFunction (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/global/featureManager.js:233:51)
    at async FeatureManager.startFeature (chrome-extension://hjpaapdjcgbmeikfnahipphknonhlhib/scripts/global/featureManager.js:142:6)
— achievements —
Achievements
— home —
Live Networth
`

**Comment by Sashank999** [comment]
Check your API key again. Use a new one if possible. TornTools uses a Limited Access key.
